Wrap variables in quotes and use printf

diff --git a/bin/prep-release b/bin/prep-release
--- a/bin/prep-release
+++ b/bin/prep-release
@@ -13,37 +13,37 @@ if [ -z "$1" ]; then
 fi
 
 if ! [ "$(git symbolic-ref --short HEAD)" = "master" ]; then
-  printf "must be on master branch to run\n" >&2
+  echo "must be on master branch to run" >&2
   exit 1
 fi
 
 if ! git diff-index --quiet HEAD --; then
-  printf "commit or stash your workspace changes\n" >&2
+  echo "commit or stash your workspace changes" >&2
   exit 1
 fi
 
-version=$1
+version="$1"
 old_version=$(< VERSION)
 branch="release-$version"
 
 if ! make test; then
-  echo "test failure, not releasing" >&2
+  echo "test suite failed. not releasing" >&2
   exit 1
 fi
 
 printf "RELEASE %s => %s\n" "$old_version" "$version"
-git checkout master
-git pull
+git fetch origin master
+git reset --hard origin/master
 
 git checkout -b "$branch"
 
 printf "%s\n" "$version" > VERSION
 make Gemfile.lock
 git add VERSION Gemfile.lock
-git commit -m "Release v$version"
+git commit --message "Release v$version"
 git push origin "$branch"
 
-branch_head=$(git rev-parse --short $branch)
+branch_head=$(git rev-parse --short "$branch")
 if command -v hub > /dev/null 2>&1; then
   hub pull-request -F - <<EOF
 Release v$version
